### ISSUE TITLE
Undocumented dependency on nasm

### ISSUE THREAD

**Issue by ldub** [wickedest/mergely-webpack#1]
I am trying to install and host mergely on a RHEL5 VM.

Here is initial log:

<details><summary>click to show intial 'npm install' log</summary><p>

```
$ npm install
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/lev/hosted-tools/mergely-webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> cwebp-bin@4.0.0 postinstall /home/lev/hosted-tools/mergely-webpack/node_modules/cwebp-bin
> node lib/install.js

  ⚠ The `/home/lev/hosted-tools/mergely-webpack/node_modules/cwebp-bin/vendor/cwebp` binary doesn't seem to work correctly
  ⚠ cwebp pre-build test failed
  ℹ compiling from source
  ✔ cwebp built successfully

> gifsicle@3.0.4 postinstall /home/lev/hosted-tools/mergely-webpack/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> mozjpeg@4.1.1 postinstall /home/lev/hosted-tools/mergely-webpack/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/home/lev/hosted-tools/mergely-webpack/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/home/lev/hosted-tools/mergely-webpack/node_modules/mozjpeg/vendor" --bindir="/home/lev/hosted-tools/mergely-webpack/node_modules/mozjpeg/vendor" --libdir="/home/lev/hosted-tools/mergely-webpack/node_modules/mozjpeg/vendor" && make --jobs=36 && make install --jobs=36
Command failed: ./configure --disable-shared --prefix="/home/lev/hosted-tools/mergely-webpack/node_modules/mozjpeg/vendor" --bindir="/home/lev/hosted-tools/mergely-webpack/node_modules/mozjpeg/vendor" --libdir="/home/lev/hosted-tools/mergely-webpack/node_modules/mozjpeg/vendor"
configure: error: no nasm (Netwide Assembler) found

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

> optipng-bin@3.1.4 postinstall /home/lev/hosted-tools/mergely-webpack/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> pngquant-bin@4.0.0 postinstall /home/lev/hosted-tools/mergely-webpack/node_modules/pngquant-bin
> node lib/install.js

  ⚠ The `/home/lev/hosted-tools/mergely-webpack/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/home/lev/hosted-tools/mergely-webpack/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mergely-webpack@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lev/.npm/_logs/2018-04-11T21_21_55_154Z-debug.log
```
---
</p></details>
<br/>

Note the error `configure: error: no nasm (Netwide Assembler) found`

I was able to install NASM v2.07:

```
$ nasm -v
NASM version 2.07 compiled on Jan 17 2011
```

However, `npm install` still fails:

<details><summary>click to show 'npm install' log after installing nasm 2.07</summary><p>

```
$ npm install

> pngquant-bin@4.0.0 postinstall /home/lev/hosted-tools/mergely-webpack/node_modules/pngquant-bin
> node lib/install.js

  ⚠ The `/home/lev/hosted-tools/mergely-webpack/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/home/lev/hosted-tools/mergely-webpack/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mergely-webpack@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lev/.npm/_logs/2018-04-11T21_25_26_100Z-debug.log
```
</p></details>
<br/>

The issue with this seems to be `make sure that libpng-dev is installed`. I ran `sudo yum install libpng-devel` (this may be called `libpng-dev` on other platforms).

<details><summary>click to show final 'npm install' log</summary><p>

```
$ npm install

> pngquant-bin@4.0.0 postinstall /home/lev/hosted-tools/mergely-webpack/node_modules/pngquant-bin
> node lib/install.js

  ⚠ The `/home/lev/hosted-tools/mergely-webpack/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✔ pngquant built successfully
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mergely-webpack@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 57 packages from 22 contributors in 11.962s
```
</p></details>
<br/>

Since this seems to work (I was able to run after this), this should be documented in the main readme.

**Comment by wickedest** [comment]
Thanks - it is an unnecessary dependency.  I've pushed an update.
